/**
 * AUTO-GENERATED by generate-country-info.ts — do not hand-edit.
 * Regenerate with `npm run generate:country-info`.
 *
 * Flags: flagcdn.com (Flagpedia, public domain), embedded as data URIs.
 * Summaries: Wikipedia page summaries, CC BY-SA 4.0 — any surface showing
 * them must attribute Wikipedia and link to the article (wikiUrl).
 */

export interface CountryInfo {
  iso3: string;
  name: string;
  flagDataUri: string;
  summary: string;
  wikiUrl: string;
}

export const COUNTRY_INFO: CountryInfo[] = [
  {
    "iso3": "BRN",
    "name": "Brunei",
    "flagDataUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAMAAABevo0zAAABKVBMVEUAAAClDB366VPVNCGMDBgKBQPRLT/34Bf////PECYcAgT44iV3DxT99r3886bQHCrZRCD+/fy7DiHpjpglIBL55Tn48PHvr7bVPyBTBg7eYB4rBAj+++BeXVf//fAVFAvu1RX77Grv6OfplhtCBAvyub/ZQlJ3bAr773378It6eXWop6NEOzhuamrusRnkeX3bSlfTKSJqBxHbSiDdVGM4MwRKQwYtLCqKfQzz3BagkQ7c3Nz9+dNNTU3+9Pbmm6Pib3zgdRzUVR3QIyibHiLcUB/0yM3QvRPBrxGwnw9ZUQqYmJjhwxXizhSysrLMzMx5Mg/419vnhZDzzhiuMhrPGCSLi4toXgn78JW3phCQkJCnbBL00hfeYm/T09O+vr7ExMShUBW7Jx3Q7hJdAAACdUlEQVRIx63WeXOaQBgG8CUcspQERIOAtVoPkqbe2JqmjbembZLWMz2StGm//4foshDHKCBp9vlHxhl+w77LA4AI4QDi4D5pkH+x+2rnGUkQ5zkx1QUdde9whyhoJ/ph7+U+SdBRd7//t+oJ4jzcrFnuyeByrFid1cpEQBx7rLPcDTkQJWZWK+HGClI/78KA1WqVD9UBgMI2S+e/ogFcK9EetWPtltuBwyAV3Ictll6/9+SiCQ5CSYKwn4hu7wB4kPTp0Zfs+mq5BgJxTG66tQNgM/HTq9+qvVD3vAInmZwEOY7rFNxLbK3crWsdAD5pps7blYR9SoFXJzG1UVWnE3S59j+JSsG/A8A/LDNAYx05J8c6zs+I57OV26x/BwJAQIkUC8QiHuvUAdsVXjU7ZkAHQKrpCyYVhQFMHm8Wx6kYbPANiZsE3GLonZL5ePw57inmIQWYOj6siyCOOnDb4E1Y4INBnMyng7fpjUtEoKjgQ4bBY6UHJQ6OwoA4FycHb9g1UKd1+xBil5FFQMFk8cinA+ugnXdnJ9/uVQGBrCYl0ZGiCADosiwgUPDrgCfoqM5Y8/YAx5YksjrD6IJYM9DC63ib3A6kru7UMKAz1h9/xqIAknNNXjAMRdFWV8kDoZ7XNzrwNRoGxLm8hoOBbBm0JNP9ObNI+pRg+WjZBua0vjHs9uCCrs3rf4cSpfsXIY02K7sFzGgQyj1YM4xur2/RNIQUC4ITDF6Ucxqka9ZQ1mjakKF2PY4/CcSrLmdyPcvoliM3+M136dWBx4ARrwf+egceBfpltQNEwNUOkAPdDhwvx0ruU9PdLMJfxGfkP9pJg/8AoVSHKF2eAkoAAAAASUVORK5CYII=",
    "summary": "Brunei, officially Brunei Darussalam, is a country in Southeast Asia, situated on the northern coast of the island of Borneo. Apart from its coastline on the South China Sea, it is completely surrounded by the Malaysian state of Sarawak, with its territory bifurcated by the Sarawak district of Limbang.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Brunei"
  },
  {
    "iso3": "KHM",
    "name": "Cambodia",
    "flagDataUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAAzCAMAAAA3r39rAAAAjVBMVEXgACXU1NTe3t7q6urHx8fSACLR0dEDLqE6I4LKysr09PS2tba/v7/MzMzFxcXEw8Owrq/Ozs6qqam9srS9qqzJIj26urrLDCza2trm5ubcASTXACLFFjTNASKweoO+mJ60h47j4uLKu72sWGbPoKehoKDAOlDGYXHDUmTBZ3Whj5LXDi/OOlLTdoXx8fEbmjpjAAABtUlEQVRYw+2We2+bMBTFY2K83fqNeYcEDEnzWNvv//Fqm7bSNO0PPKRKE0dIPlyJn3x9jOXdj5W124AbcAN+C/Dnytp9l9pfK/OmqV0VWF0ux1UneKPqeRVSMQ9pz1if/laK0zPqZkgOcJ5JRf0PxMNQ3kMW1YjFWIXm7+XpEB/FqHOfRXpjRI+TBx1zYqpo3pXb8eY7HwzRZvCx3KSFa+SeTE89d18XXTeBbhoup64r7mB5H9n0MTsTgnJFCKMXIS+UEaJyREifxe3JVD2oNY8MY8oU0YpRjLOHsfSh0rieh0QgaSVCuKk5ry1G4VUkQ2QoJ+ANAJWSojpJauQd4IbjUyyQyYTJjNJME4QI906yRLJIYDGoTGUmNyanVClaemdcSQ1RP8uhx5KJEgeVAB+OCiZxH7Nv7qBBAtNBLDzBuaLG1+Wn43F0OWAQSRB3qNlJEC6hcfFObM/7/d5lzPdBtdb17FypccN56RRf3IEFWAq3eF4l8E8nJHZD/rIQ+Prk9Oam8xRkAezsHOzNj69LM069qq5KZ3Xdh/ksRR6KXyvVtn+U/qLVbw7bdW4DbsD/AvgONWpaV3ctZk8AAAAASUVORK5CYII=",
    "summary": "Cambodia, officially the Kingdom of Cambodia, is a country in Mainland Southeast Asia. It is bordered by Thailand to the northwest, Laos to the north, and Vietnam to the east, and has a coastline along the Gulf of Thailand in the southwest.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Cambodia"
  },
  {
    "iso3": "IDN",
    "name": "Indonesia",
    "flagDataUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1AgMAAACrRoTXAAAACVBMVEX/AAD/////f3/sDLJDAAAAG0lEQVQ4y2NgGAWjAC9YhQUwhGIBo4KjgnAAAA8AufGM9Lq4AAAAAElFTkSuQmCC",
    "summary": "Indonesia, officially the Republic of Indonesia, is a country in Southeast Asia and Oceania, between the Indian and Pacific oceans. Comprising over 17,000 islands, including Sumatra, Java, Sulawesi, and parts of Borneo and New Guinea, Indonesia is the world's largest archipelagic state and the 14th-largest country by area, at 1,904,569 square kilometres.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Indonesia"
  },
  {
    "iso3": "LAO",
    "name": "Laos",
    "flagDataUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1BAMAAAAkBnF3AAAAMFBMVEUAKGj////OESY0Iljc4eoWOnV2i65ddp/y9PfI0N+zv9KptsySo74GLWs/XY0sTIJXQT/FAAAAk0lEQVRIx2NQIhIwjCocOQqNiQQMdACs1R4t2wMIq+PNEASCtgsEFUYKgsFUghY7QhSKELKcSxAKFhBQWAhTKE5AoSNMoQh+dfyCcPABr0I2hMIEvAp5EAoPEOdpQcEN1DGRaDfeQyh8QJ1wJD5mOGEKJ1Ar9cDS41IiU3g7MXkmRdA77wI9cifRJcVoiTuqEB0AAAqWtzyUzKPyAAAAAElFTkSuQmCC",
    "summary": "Laos, officially the Lao People's Democratic Republic (LPDR), is a country in Mainland Southeast Asia, and the only landlocked country in Southeast Asia. It is bordered by Myanmar and China to the northwest, Vietnam to the east, Cambodia to the southeast, and Thailand to the west and southwest. Laos has a population of more than 7.5 million, and its capital and most populous city is Vientiane.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Laos"
  },
  {
    "iso3": "MYS",
    "name": "Malaysia",
    "flagDataUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAMAAABevo0zAAAAPFBMVEUAAGYzAE0XElzywQXYPz/yv7//zADMAAD////lf39NPUbBmhh1XTbTqBE5LU8qIlWTdiphTj5/ZTOqiCG9Hr0CAAABDUlEQVRIx9WVzW7EIAyEXXt3tmtM+Mn7v2tPASJFFSFslc6Ji0c232CIOvXqFH3ccOFjw0en9lW6CvxqR57fndrZCXxiIppkGIG4nQOFQKE1fHaqVqTGjzKpUr4EhQV+OyppNotKyuOGBmgh7RZxTha31A7fnSoFK2RrkEkhgECJeRhKnZiS9wIA4l0apsyAq/NlAABaKqdHrh0Gc6XDmvHTUFy5Q6J6hxdiE4H0G+XTwQ6AcMlhMrOc2hyef3rWYjFSJbv+lv3WEVMI+x0xsr4MwKp8vG2GFmzIDhAf+S++gJEFO8fwq1PdOXxN1nzDx2R1X3Y3lOmG78n6B5Snj3x/ytODfX/Kz8m6P+UfevBF/xzUcWoAAAAASUVORK5CYII=",
    "summary": "Malaysia is a country in Southeast Asia. A federal constitutional monarchy, it consists of 13 states and three federal territories, separated by the South China Sea into two regions: Peninsular Malaysia on Mainland Southeast Asia and East Malaysia on the island of Borneo.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Malaysia"
  },
  {
    "iso3": "MMR",
    "name": "Myanmar",
    "flagDataUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1CAMAAADh9px2AAAAXVBMVEX////rMUFUv1T+8/S7wxGuVDfN7cz+ywDqKDk0sjOf25/8+eHh9ODG6sb/6Y8/tj7+1zrwZXHxc37vyMXv+e99znztSFf82dxtyG34tbv4sbe7wxCtVTf1nKT0k5szDlc+AAABLUlEQVRYw+3S2XKDIBSA4QMkNmURl5jEbO//mDFiOpYqHJabzniulNFPfwW+Mg9s4Ab+I7CqMoNlmRkUIi9YAVRZwRKgzAoKAJETHIqxzYAtxjbDbeefm3iDYoe5FL4RQ2EcirkWBXID8mygNKDMBU7FuOZlkKpiNvIDyvmqoiFvSH+QtZE0LFlzt8d18De8HNe54yXmp9BizSto5F9eyebx22Yp25GL2Ida2Z7SiRubB+SiwO432CWDVrNKBbX9DXUi2Nmgrxnue9fcWxts9+4b4OAcMjHn0+lsjhhx3+EBG6NcB4VczXGTBPbjS01Gw95nfQpI2Jj7OR2zPc3gLX7MFx7DQp0A9sCs22vmaQZ3cfunj7TuZidYPxcecnjW8W8YtIzaNuGzgRsYMS9F93kAqN1/mQAAAABJRU5ErkJggg==",
    "summary": "Myanmar, officially the Republic of the Union of Myanmar and also referred to as Burma, is a country in northwest Southeast Asia. It is the largest country by area in Mainland Southeast Asia and has a population of about 55 million.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Myanmar"
  },
  {
    "iso3": "PHL",
    "name": "Philippines",
    "flagDataUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAMAAABevo0zAAAAk1BMVEX////+6Ib94Wn95Hb+8rr//vT+76vOESYAOKj80RX93VD/++b+65j/9Mb94GD+7aP81Cb/99X91zT7/P5pis3BzurVNUb76uz43ODk6vYQRa7RGy8hUrT08/gHParTJjnpkpyKpNfhaXfaSFnT3PBBar7keobdV2ZUesbspa3ywMWftN720dUyX7n++PnvsrisvuJ0e8aBAAABXElEQVRIx62W6XLCMAyE5Stq7pPQQoCe9KKl7/90DUkMpg3DxNb+9Ey+sVcrRTBrbkgFUD4saIEAdxUtMAT1/EIJDBIJ8NOQAVPfb4GtlWuqG3oshs7KNzIPtWZfNFU29LkgBsKqWtMCna08Y0kCK01eng31KR2sNIFREblbOQAYZ23EkxQUC9LuxLYb9Wu58EAK2UJFrlPZOADDSPAk8wuesEgNZ6XVYDtVOPMPKuKzCFWWwDRWnt8rVtLrDxXIcLqV3aceEzwYgAEXrM+jCrLD8ycOtuvA/Qan6NqTd0+IFkCjKLlZlPkjoh3QiE2qYwPf90u0Beac/wv2R41oDexbLzBa7/YV0QH4dzjMt4juwOP4gvcNUgAhdjFvDOhk3gXgartESqCDeSfg6Uc/uc/GgXoVseizUWDUL0tWfTZ+w26d29eIVMB24aQwz6gyjXlHYElkngbuaiTVLzAfWkblawOMAAAAAElFTkSuQmCC",
    "summary": "The Philippines, officially the Republic of the Philippines, is an archipelagic country in Southeast Asia. Located in the western Pacific Ocean, it consists of about 7,641 islands, with a total area of about 300,000 square kilometers, which are broadly categorized in three main geographical divisions from north to south: Luzon, Visayas, and Mindanao.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Philippines"
  },
  {
    "iso3": "SGP",
    "name": "Singapore",
    "flagDataUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1CAMAAADh9px2AAAANlBMVEXtKTnza3b+7e/94uXuMUDwSljvPEr////2k5vxXGj82Nv0eYP3nqX6ub/1i5P/+/z7ys74rLPXG5EHAAAA50lEQVRYw+3US3LEIAxF0cf3trANeP+bzcDuBaTEKEEjlwenkJ5A+u+VrR9lHXe0QQp5FVcmjPPhwgLvM6CZJMmOae7GcwI+z7dFLnfjN9C+SkuH16sDOCRZlbLJvIMMAEXVrtOecxZLwRyRAFFSH/E9WL1ojmQmcEmy2er767yno+UIdElF+QsWVUfUFzBXXuIOjHd4byg+8E1Zkvqzg8252gk4n3C5sywSfcttA4ZJqjFmST3dzimeQMqS1VIkBfeLk79Nr6sQIYalpPUrzqNk7frVu7W4xOLa4AY3uMENbnCDfxj8AW3FQWspoZQjAAAAAElFTkSuQmCC",
    "summary": "Singapore, officially the Republic of Singapore, is an island country in Southeast Asia. Its territory comprises a main island, over 60 satellite islands and islets, and one outlying islet.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Singapore"
  },
  {
    "iso3": "THA",
    "name": "Thailand",
    "flagDataUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1BAMAAAAkBnF3AAAAD1BMVEWlGTEtKkr09fiyP1Oysr55zkMlAAAANUlEQVRIx2NgGAVUAcZEAgYlIsGoQvwKXYgEDIJEglGFowoHlUKiU/hoSUEdhUSX4aOAKgAAbROnWeiw6CoAAAAASUVORK5CYII=",
    "summary": "Thailand, officially the Kingdom of Thailand, and formerly known as Siam, is a country located in Mainland Southeast Asia. It shares land borders with Myanmar to the west and northwest, Laos to the east and northeast, Cambodia to the southeast, and Malaysia to the south.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Thailand"
  },
  {
    "iso3": "VNM",
    "name": "Vietnam",
    "flagDataUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAA1BAMAAAAkBnF3AAAALVBMVEX/AAD/6wD/dgD/BwD/LgD/swD/2wD/ywD/lAD/GQD/TAD/ggD/QQD/5AD/aABQeZ7QAAAA3UlEQVQYGe3BMUoDQRiG4RdHTIyy8Im7BjEgOcEUdiLEKoXVlnZubxEhB0hKuzT28QaKF9DGPniBPYrJEILNzvytsM9D6x9xHpveEpvuDJubH2xez7GZ9zFxVeGxOJY+sehKMywOpAcsvqQL4rLhRinlw42aJoel/sgXNMpW2hnUNHNj7UyJcXNt9T1RvUpBsSTOvSi4J8VXWitIulIwIuVIwRspHQUTUm6lvJROSXmXPq6lE1Ke9AjfOiNhX/kCXKkRcXuDmrVsdUlcZ0ownhB35wncM3GeLUerlfALhNEipD22nCoAAAAASUVORK5CYII=",
    "summary": "Vietnam, officially the Socialist Republic of Viet Nam (SRV), is a country at the eastern edge of Mainland Southeast Asia. With an area of about 331,000 square kilometres and a population of over 102 million, it is the world's 16th-most populous country.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Vietnam"
  },
  {
    "iso3": "TLS",
    "name": "Timor-Leste",
    "flagDataUri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAMAAABevo0zAAAASFBMVEUAAAAIBgHUpST3wCr1nyj///8sIgfaKRz/xyzjUCChfRtaOg5vb28aGhrV1dVeSQ8xMTGkpKSOjo7u7u65ublBQUHKhCAMDAy+9pVmAAAA8UlEQVRIx7XXwRaCIBAF0GeGaQEKav3/nyagmcYGeM3GlfecdwaZEY/uRi2geXZcENX92lFBoK95pAfRXFoWGcAldksisVVfc8gP6GIzyB30sctJfJeLXUoewBC7jDyCa+wSEucKsfPJH3CLnUuuiozEziNXxFj/GI6xc8gVtELiJfV8jp1ObpGFmEZhIrFTyR1cSkW6nUr6l+fJezbe7TTSdUKLUOPAAVEN0gRRkSIvNQptjdaK1RRo4fJWinVsMJloh7MPNqzifnpQ5Mvhb9cX+4JljwDykGKPUfagJ68i7GWJvc6RF072Ssxe2tm/FW8TQU3LWdiRcgAAAABJRU5ErkJggg==",
    "summary": "Timor-Leste, also known as East Timor, officially the Democratic Republic of Timor-Leste, is a country in Southeast Asia. It comprises the eastern half of the island of Timor, the coastal exclave of Oecusse in the island's northwest, and the islands of Atauro and Jaco, for a total land area of 15,007 square kilometres (5,794 sq mi).",
    "wikiUrl": "https://en.wikipedia.org/wiki/Timor-Leste"
  }
];
