/**
 * Codegen: writes src/dashboard/country-info.ts — flag images and short
 * Wikipedia summaries for the 11 SEA countries (docs/adr/0001).
 *
 * Run via `npm run generate:country-info`. This is the ONLY place that
 * touches the network for country info: the dashboard build itself stays
 * offline/self-contained, reading the committed generated module. Re-run
 * only when a summary looks stale — the country set is fixed by ADR-0001.
 *
 * Sources & licensing:
 * - Flags: flagcdn.com (Flagpedia) w80 PNGs, public domain, embedded as
 *   data URIs.
 * - Summaries: Wikipedia REST API page summaries, CC BY-SA 4.0 — the
 *   dashboard must attribute and link back to the article (it does, in the
 *   country panel), mirroring how ADR-0015 treats ReliefWeb attribution.
 */

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const OUT_URL = new URL("./country-info.ts", import.meta.url);
const FETCH_TIMEOUT_MS = 20_000;

// Wikimedia etiquette: identify the client.
const USER_AGENT = "hadr-monitor/0.1 (codegen; run manually)";

/** The fixed ADR-0001 country set. wikiTitle is the English Wikipedia article
 * title (Timor-Leste's article lives at "East Timor"). iso2 keys flagcdn. */
const COUNTRIES = [
  { iso3: "BRN", iso2: "bn", name: "Brunei", wikiTitle: "Brunei" },
  { iso3: "KHM", iso2: "kh", name: "Cambodia", wikiTitle: "Cambodia" },
  { iso3: "IDN", iso2: "id", name: "Indonesia", wikiTitle: "Indonesia" },
  { iso3: "LAO", iso2: "la", name: "Laos", wikiTitle: "Laos" },
  { iso3: "MYS", iso2: "my", name: "Malaysia", wikiTitle: "Malaysia" },
  { iso3: "MMR", iso2: "mm", name: "Myanmar", wikiTitle: "Myanmar" },
  { iso3: "PHL", iso2: "ph", name: "Philippines", wikiTitle: "Philippines" },
  { iso3: "SGP", iso2: "sg", name: "Singapore", wikiTitle: "Singapore" },
  { iso3: "THA", iso2: "th", name: "Thailand", wikiTitle: "Thailand" },
  { iso3: "VNM", iso2: "vn", name: "Vietnam", wikiTitle: "Vietnam" },
  { iso3: "TLS", iso2: "tl", name: "Timor-Leste", wikiTitle: "East Timor" },
] as const;

/** Truncates a summary at a sentence boundary near ~400 chars, so the panel
 * stays a short read rather than a full lede paragraph. */
function truncateAtSentence(text: string, limit = 400): string {
  if (text.length <= limit) return text;
  const sentences = text.split(/(?<=[.!?])\s+/);
  let out = "";
  for (const s of sentences) {
    if (out.length > 0 && out.length + s.length + 1 > limit) break;
    out = out.length === 0 ? s : `${out} ${s}`;
  }
  return out.length > 0 ? out : text.slice(0, limit);
}

async function fetchFlagDataUri(iso2: string): Promise<string> {
  const res = await fetch(`https://flagcdn.com/w80/${iso2}.png`, {
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  if (!res.ok) throw new Error(`flagcdn ${iso2}: HTTP ${res.status}`);
  const b64 = Buffer.from(await res.arrayBuffer()).toString("base64");
  return `data:image/png;base64,${b64}`;
}

interface WikiSummary {
  extract?: string;
  content_urls?: { desktop?: { page?: string } };
}

async function fetchWikiSummary(wikiTitle: string): Promise<{ summary: string; wikiUrl: string }> {
  const title = encodeURIComponent(wikiTitle.replace(/ /g, "_"));
  const res = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${title}`, {
    headers: { "User-Agent": USER_AGENT, Accept: "application/json" },
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
  if (!res.ok) throw new Error(`wikipedia ${wikiTitle}: HTTP ${res.status}`);
  const data = (await res.json()) as WikiSummary;
  const extract = typeof data.extract === "string" ? data.extract.trim() : "";
  if (!extract) throw new Error(`wikipedia ${wikiTitle}: empty extract`);
  const wikiUrl =
    data.content_urls?.desktop?.page ??
    `https://en.wikipedia.org/wiki/${title}`;
  return { summary: truncateAtSentence(extract), wikiUrl };
}

async function main(): Promise<void> {
  const entries = [];
  for (const c of COUNTRIES) {
    // Sequential on purpose: 22 tiny requests, politeness over speed for a
    // manually-run codegen script.
    const [flagDataUri, wiki] = await Promise.all([
      fetchFlagDataUri(c.iso2),
      fetchWikiSummary(c.wikiTitle),
    ]);
    entries.push({
      iso3: c.iso3,
      name: c.name,
      flagDataUri,
      summary: wiki.summary,
      wikiUrl: wiki.wikiUrl,
    });
    console.log(`[country-info] ${c.name}: flag ok, summary ${wiki.summary.length} chars`);
  }

  const header = `/**
 * AUTO-GENERATED by generate-country-info.ts — do not hand-edit.
 * Regenerate with \`npm run generate:country-info\`.
 *
 * Flags: flagcdn.com (Flagpedia, public domain), embedded as data URIs.
 * Summaries: Wikipedia page summaries, CC BY-SA 4.0 — any surface showing
 * them must attribute Wikipedia and link to the article (wikiUrl).
 */

export interface CountryInfo {
  iso3: string;
  name: string;
  flagDataUri: string;
  summary: string;
  wikiUrl: string;
}

export const COUNTRY_INFO: CountryInfo[] = `;

  await writeFile(OUT_URL, header + JSON.stringify(entries, null, 2) + ";\n", "utf8");
  console.log(`[country-info] Wrote ${fileURLToPath(OUT_URL)} (${entries.length} countries).`);
}

main().catch((err) => {
  console.error("[country-info] Generation failed:", err);
  process.exitCode = 1;
});
